### PR TITLE
breaking change:complete conversion from Ozone to Ozone3

### PR DESCRIPTION
**Pull request by iamnandhu**
changed every instance of Ozone and ozone in the package to Ozon3 and ozone3 respectively including file names, class names and in docs

### CODE REVIEW

**Review by Milind220 — CHANGES_REQUESTED** [review]
Hey, if you look at the issue title and description carefully, you can see that it says change all mentions of ozone to ozon3, not ozone3. 

ozon3 is the name of this package on PyPI, and this issue aims to add uniformity to the rest of the package.

Could you make this change please?

**Comment by iamnandhu** [comment]
> Hey, if you look at the issue title and description carefully, you can see that it says change all mentions of ozone to ozon3, not ozone3.
> 
> ozon3 is the name of this package on PyPI, and this issue aims to add uniformity to the rest of the package.
> 
> Could you make this change please?

could you brief it please? 
so am I to change mentions of ozone in docs and comments and not tamper with the source codes

**Comment by Milind220** [comment]
> > Hey, if you look at the issue title and description carefully, you can see that it says change all mentions of ozone to ozon3, not ozone3.
> > ozon3 is the name of this package on PyPI, and this issue aims to add uniformity to the rest of the package.
> > Could you make this change please?
> 
> could you brief it please? so am I to change mentions of ozone in docs and comments and not tamper with the source codes

Let me make this as clear as I can:

You changed everything to `ozone3`.
It should be `ozon3`

ozone3 vs ozon3 - Don't add an 'e' at the end :)

This issue describes changing it EVERYWHERE. Source code, documentation, everything.

**Comment by Milind220** [comment]
@iamnandhu Hey! If you're no longer available to finish this pull request, please let me know and I'll delete it

If you want to finish it, but still need help understanding what to do, I can explain it again :)

**Pull request closed without merging**
